version: "3"

services:
  # Base nginx configuration for all projects 
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
  
networks:
  default:
    external:
      name: nginx-proxy
